mod agent_slide;
mod ai_access_slide;
mod ai_setup_slide;
mod bottom_nav;
mod customize_slide;
mod intention_slide;
mod intro_slide;
pub mod layout;
mod offer_slide;
mod onboarding_slide;
mod progress_dots;
pub mod slide_content;
mod theme_picker_slide;
mod third_party_slide;
mod toggle_card;
mod two_line_button;
mod upgrade_auth_prompt;

pub use agent_slide::{AgentAutonomy, AgentDevelopmentSettings, AgentSlide, OnboardingModelInfo};
pub use ai_access_slide::{AiAccessSlide, AiAccessSlideEvent};
pub use ai_setup_slide::AiSetupSlide;
pub use bottom_nav::onboarding_bottom_nav;
pub use customize_slide::CustomizeUISlide;
pub use intention_slide::IntentionSlide;
pub use intro_slide::{IntroSlide, IntroSlideEvent};
pub use offer_slide::{OfferSlide, OfferSlideEvent, OfferVariant};
pub use onboarding_slide::OnboardingSlide;
pub use theme_picker_slide::{ThemePickerSlide, ThemePickerSlideEvent};
pub use third_party_slide::ThirdPartySlide;
